### ISSUE TITLE
YAMLException

### ISSUE THREAD

**Issue by herghost** [nodeca/js-yaml#324]
Removed and readded library, get this at boot

```
YAMLException: bad indentation of a mapping entry at line 1677, column 16:
0|app      |                 get:
0|app      |                    ^
0|app      |     at generateError (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
0|app      |     at throwError (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
0|app      |     at readBlockMapping (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1075:7)
0|app      |     at composeNode (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
0|app      |     at readBlockMapping (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
0|app      |     at composeNode (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
0|app      |     at readBlockMapping (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1057:11)
0|app      |     at composeNode (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
0|app      |     at readDocument (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
0|app      |     at loadDocuments (/home/dave/handler/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)

```

**Comment by herghost** [comment]
Apologies, this was actually an erorr in a completely unrelated file
