### ISSUE TITLE
Support `$.dump(obj, { noRefs: true })` where obj contains cyclic references

### ISSUE THREAD

**Issue by erikerikson** [nodeca/js-yaml#387]
using `"version": "3.10.0"`, if I run the following code:
```
const yaml = require('js-yaml')

const obj = {
    bar: 'baz'
}

obj.foo = obj

yaml.dump(obj, { noRefs: true })
```

I expect to see:
```
bar: baz
```

Instead, I observe:
```
/[...] $node index.js
/[...]/node_modules/js-yaml/lib/js-yaml/type/timestamp.js:25
  if (YAML_TIMESTAMP_REGEXP.exec(data) !== null) return true;
                            ^

RangeError: Maximum call stack size exceeded
  at RegExp.exec (native)
  at Type.resolveYamlTimestamp [as resolve] (/[...]/node_modules/js-yaml/lib/js-yaml/type/timestamp.js:25:29)
  at testImplicitResolving (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:166:14)
  at testAmbiguity (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:344:14)
  at chooseScalarStyle (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:300:22)
  at /[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:347:13
  at writeScalar (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:363:4)
  at writeNode (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:744:9)
  at writeBlockMapping (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:606:10)
  at writeNode (/[...]/node_modules/js-yaml/lib/js-yaml/dumper.js:720:9)
```

I found this investigating https://github.com/serverless/serverless/issues/4556.

**Comment by puzrin** [comment]
Dumper does not track infinite loops. It's user's responsibility to sanitize data. `norefs` works when you pin the same object to multiple properties - then it creates copies, instead of refs.
