### ISSUE TITLE
Can't resolve a node with '!!js/function'

### ISSUE THREAD

**Issue by Kerminate** [nodeca/js-yaml#448]
My yaml code is as follows:

```
confirm_password:
  - required: true
    message: '请填写确认密码'
  - validator: !!js/function >
    function validator(ctx) {
      return async function (rule, value, callback, source, options) {
        if (ctx.request.body.password === value) {
          await callback();
        }
        callback([{ message:'密码与确认密码不匹配', field:'confirm_password' }])
      }
    }
```

But encountered an error:
```
{ YAMLException: cannot resolve a node with !<tag:yaml.org,2002:js/function> explicit tag at line 15, column 5:
        function validator(ctx) {
        ^
    at generateError (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:171:9)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1393:9)
    at readBlockMapping (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockSequence (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:928:5)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/Users/kepeilin/Documents/web-projects/diao/node_modules/_js-yaml@3.12.0@js-yaml/lib/js-yaml/loader.js:1569:19)
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_pipe.js:3:14
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/cond.js:47:30
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at R.tryCatch.path (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:61:23)
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/tryCatch.js:33:20
    at /Users/kepeilin/Documents/web-projects/diao/node_modules/_ramda@0.25.0@ramda/src/internal/_arity.js:10:19
    at Array.forEach (<anonymous>)
    at Object.loadDocs (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:70:11)
    at Object.get docs [as docs] (/Users/kepeilin/Documents/web-projects/diao/node_modules/_egg-y-validator@1.1.7@egg-y-validator/app/extend/context.js:75:17)
```

what should i do?

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#load-string---options-

I guess, use `load` instead of `safeLoad`.
