### ISSUE TITLE
Is it possible to load ".env.local.example" file with undefined variables?

### ISSUE THREAD

**Issue by Vadorequest** [nodeca/js-yaml#617]
I'm trying to load a `.env.local.example` file where the YAML variables are not defined

```js
const variables = yaml.load(fs.readFileSync('./.env.local.example', 'utf-8'))
console.log('variables', variables)
```

I get the following error:
```
YAMLException: end of the stream or a document separator is expected (31:1)

 28 | # Used to send monitoring event ...
 29 | # Optional - If not set, the ap ...
 30 | # Example (fake value): https:/ ...
 31 | SENTRY_DSN=                     ...
------^
 32 | 
 33 | # Github "personal access token ...
    at generateError (/Users/vadorequest/dev/unlyEd/chatbot-builder/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/Users/vadorequest/dev/unlyEd/chatbot-builder/node_modules/js-yaml/lib/loader.js:187:9)
    at readDocument (/Users/vadorequest/dev/unlyEd/chatbot-builder/node_modules/js-yaml/lib/loader.js:1645:5)
    at loadDocuments (/Users/vadorequest/dev/unlyEd/chatbot-builder/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/Users/vadorequest/dev/unlyEd/chatbot-builder/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.<anonymous> (/Users/vadorequest/dev/unlyEd/chatbot-builder/next.config.js:32:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  reason: 'end of the stream or a document separator is expected',
  mark: {
    name: null,
    buffer: '# XXX Template example\n' +
      '# This file is an example, meant to be duplicated as ".env.local" for local override\n' +
      '\n' +
      '# See https://nextjs.org/docs/basic-features/environment-variables\n' +
      '\n' +
      '# XXX Tips: How is this file meant to be used?\n' +
      '# This file is NOT tracked by git and can contain sensitive information, or override variables from ".env".\n' +
      '\n' +
      '# XXX Tips: When is this file being used?\n' +
      "# This file is used only when building the Next.js app locally (localhost), whether it's for running `next dev` or `next build`.\n" +
      '# For staging/production stages, the app relies on "vercel.{NEXT_PUBLIC_CUSTOMER_REF}.{NEXT_PUBLIC_APP_STAGE}.yml:build.env".\n' +
      '\n' +
      `# XXX Tips: What's the difference between env vars starting with "NEXT_PUBLIC_" and the others?\n` +
      `# All env variables that DON'T start with "NEXT_PUBLIC_" MUST be manually exposed by ./next.config.js for the project to work locally\n` +
      '# "NEXT_PUBLIC_" has a semantic purpose. If you mean to use a variable on the browser, then you should use "NEXT_PUBLIC_".\n' +
      '# Any non-sensitive env variable should start with "NEXT_PUBLIC_".\n' +
      '# Sensitive information MUST NOT start with "NEXT_PUBLIC_".\n' +
      `# You must be careful to use sensitive information only on the server-side, because if you use them on the browser or getInitialProps, they'll be leaked, even if the variable doesn't start with "NEXT_PUBLIC_".\n` +
      '# Any change to this file needs a server restart to be applied.\n' +
      '\n' +
      '# Locize API key, can be found under "Your project > Settings > Api Keys" at https://www.locize.app/?ref=unly-nrn\n' +
      '# Used to automatically save missing translations when working locally\n' +
      "# Optional - If not set, the app will work anyway, it just won't create new keys automatically\n" +
      '# Example (fake value): 615384ff-0f39-4c7b-89ca-9b0acbfd0869\n' +
      'LOCIZE_API_KEY=\n' +
      '\n' +
      '# Sentry DSN, can be found under "Your project > Client Keys (DSN)" at https://sentry.io/settings/YOUR_ORG/projects/YOUR_PROJECT/keys/\n' +
      '# Used to send monitoring events (errors, etc.)\n' +
      "# Optional - If not set, the app will work anyway, it just won't send any event\n" +
      '# Example (fake value): https://14fa1cae05079675b18cd05403ae5c48@sentry.io/1234567\n' +
      'SENTRY_DSN=\n' +
      '\n' +
      '# Github "personal access token", can be generated at "Settings > Developer settings > Personal access tokens" at https://github.com/settings/tokens\n' +
      '# Used by "Workflow Dispatch" GitHub Actions\n' +
      '# Needs the following scopes:\n' +
      '#  - Repo (FULL)\n' +
      '#  - Workflow\n' +
      `# Optional - If not set, the app will work anyway, it just won't be able to deploy new instances through the "startVercelDeployment" API\n` +
      '# Example (fake value): 278c560c1314b8b032c1314b856072bdaaaaaaaa\n' +
      'GITHUB_DISPATCH_TOKEN=\n' +
      '\n' +
      '# Server secret key for FaunaDB.\n' +
      '# Used to perform actions from the server-side (creating users, etc.)\n' +
      '# Go to https://dashboard.fauna.com/ > Select DB > Security > New Key > Role: Server | Name: FAUNADB_SERVER_SECRET_KEY\n' +
      'FAUNADB_SERVER_SECRET_KEY=\n' +
      '\n' +
      '# Magic Link provides a "secret key" which must only be used from the server.\n' +
      '# Go to https://dashboard.magic.link/ > API Keys > Test "Secret key"\n' +
      'MAGIC_AUTH_SECRET_KEY=\n',
    position: 2090,
    line: 30,
    column: 0,
    snippet: ' 28 | # Used to send monitoring event ...\n' +
      ' 29 | # Optional - If not set, the ap ...\n' +
      ' 30 | # Example (fake value): https:/ ...\n' +
      ' 31 | SENTRY_DSN= ...\n' +
      '------^\n' +
      ' 32 | \n' +
      ' 33 | # Github "personal access token ...'
  }
}
error Command failed with exit code 1.

```

Here is the file content:
```yml
# XXX Template example
# This file is an example, meant to be duplicated as ".env.local" for local override

# See https://nextjs.org/docs/basic-features/environment-variables

# XXX Tips: How is this file meant to be used?
# This file is NOT tracked by git and can contain sensitive information, or override variables from ".env".

# XXX Tips: When is this file being used?
# This file is used only when building the Next.js app locally (localhost), whether it's for running `next dev` or `next build`.
# For staging/production stages, the app relies on "vercel.{NEXT_PUBLIC_CUSTOMER_REF}.{NEXT_PUBLIC_APP_STAGE}.yml:build.env".

# XXX Tips: What's the difference between env vars starting with "NEXT_PUBLIC_" and the others?
# All env variables that DON'T start with "NEXT_PUBLIC_" MUST be manually exposed by ./next.config.js for the project to work locally
# "NEXT_PUBLIC_" has a semantic purpose. If you mean to use a variable on the browser, then you should use "NEXT_PUBLIC_".
# Any non-sensitive env variable should start with "NEXT_PUBLIC_".
# Sensitive information MUST NOT start with "NEXT_PUBLIC_".
# You must be careful to use sensitive information only on the server-side, because if you use them on the browser or getInitialProps, they'll be leaked, even if the variable doesn't start with "NEXT_PUBLIC_".
# Any change to this file needs a server restart to be applied.

# Locize API key, can be found under "Your project > Settings > Api Keys" at https://www.locize.app/?ref=unly-nrn
# Used to automatically save missing translations when working locally
# Optional - If not set, the app will work anyway, it just won't create new keys automatically
# Example (fake value): 615384ff-0f39-4c7b-89ca-9b0acbfd0869
LOCIZE_API_KEY=

# Sentry DSN, can be found under "Your project > Client Keys (DSN)" at https://sentry.io/settings/YOUR_ORG/projects/YOUR_PROJECT/keys/
# Used to send monitoring events (errors, etc.)
# Optional - If not set, the app will work anyway, it just won't send any event
# Example (fake value): https://14fa1cae05079675b18cd05403ae5c48@sentry.io/1234567
SENTRY_DSN=

# Github "personal access token", can be generated at "Settings > Developer settings > Personal access tokens" at https://github.com/settings/tokens
# Used by "Workflow Dispatch" GitHub Actions
# Needs the following scopes:
#  - Repo (FULL)
#  - Workflow
# Optional - If not set, the app will work anyway, it just won't be able to deploy new instances through the "startVercelDeployment" API
# Example (fake value): 278c560c1314b8b032c1314b856072bdaaaaaaaa
GITHUB_DISPATCH_TOKEN=

# Server secret key for FaunaDB.
# Used to perform actions from the server-side (creating users, etc.)
# Go to https://dashboard.fauna.com/ > Select DB > Security > New Key > Role: Server | Name: FAUNADB_SERVER_SECRET_KEY
FAUNADB_SERVER_SECRET_KEY=

# Magic Link provides a "secret key" which must only be used from the server.
# Go to https://dashboard.magic.link/ > API Keys > Test "Secret key"
MAGIC_AUTH_SECRET_KEY=

```

I suppose it fails because the variables don't have actual values. Is there a way to ignore those?
The goal is to get a list of all the variables, I don't care about the values.

**Comment by rlidwka** [comment]
It fails because the file you are trying to parse is **not** in yaml format.

Use https://github.com/npm/ini or something similar.

**Comment by Vadorequest** [comment]
Thank you, I didn't know it was a INI format either. Found a solution on SO that works well:
https://stackoverflow.com/questions/66950285/how-to-list-all-variables-listed-in-a-dot-env-file-e-g-env-local-example
