### ISSUE TITLE
Wrong error message when yaml file contains tabs

### ISSUE THREAD

**Issue by jtmalinowski** [nodeca/js-yaml#64]
Steps to reproduce:
1. Create otherwise valid yaml file, but instead of spaces use tabs.
2. See error when loading with require:

YAMLException: JS-YAML: the stream contains non-printable characters in "/home/developer/code/request-tester/app.yml" at line 1, column 1

What should appear:
1. Either error at appearance of first invalid character (tab)
2. or general error that there are tabs in the file

I should have some time this weekend to do the pull request here.

**Comment by WenyinWei** [comment]
Seems that this bug arises again in 3.13.1 version of js-yaml. How to fix it?

Problem appeared after I run `hexo g`

`INFO  Start processing
ERROR Process failed: languages/default.yml
YAMLException: the stream contains non-printable characters at line 1, column 10:
    IntxLNKe
             ^
    at generateError (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at captureSegment (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:261:7)
    at readPlainScalar (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:533:3)
    at composeNode (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1375:20)
    at readBlockMapping (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1036:16)
    at composeNode (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/wenyin/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)`
